services:

  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - '3306:3306'
    expose:
      - 3306
    healthcheck:
        test: ["CMD", "mysql", "-u$DB_USERNAME", "-p$DB_PASSWORD"]
        interval: 20s
        timeout: 10s
        retries: 2

  backend:
    build: .
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/usr/local/src
    ports:
      - '3000:3000'
    expose:
      - 3000
    entrypoint: /usr/local/script.sh
  
volumes:
    src: